generator < tests\0.in > tests\0odp.out
generator < tests\1.in > tests\1odp.out
generator < tests\2.in > tests\2odp.out
generator < tests\3.in > tests\3odp.out
generator < tests\4.in > tests\4odp.out
generator < tests\5.in > tests\5odp.out
generator < tests\6.in > tests\6odp.out
generator < tests\7.in > tests\7odp.out
generator < tests\8.in > tests\8odp.out
generator < tests\9.in > tests\9odp.out
generator < tests\10.in > tests\10odp.out
generator < tests\11.in > tests\11odp.out
generator < tests\12.in > tests\12odp.out
generator < tests\13.in > tests\13odp.out
generator < tests\14.in > tests\14odp.out
generator < tests\15.in > tests\15odp.out
comp tests\0.out tests\0odp.out < n.txt
comp tests\1.out tests\1odp.out < n.txt
comp tests\2.out tests\2odp.out < n.txt
comp tests\3.out tests\3odp.out < n.txt
comp tests\4.out tests\4odp.out < n.txt
comp tests\5.out tests\5odp.out < n.txt
comp tests\6.out tests\6odp.out < n.txt
comp tests\7.out tests\7odp.out < n.txt
comp tests\8.out tests\8odp.out < n.txt
comp tests\9.out tests\9odp.out < n.txt
comp tests\10.out tests\10odp.out < n.txt
comp tests\11.out tests\11odp.out < n.txt
comp tests\12.out tests\12odp.out < n.txt
comp tests\13.out tests\13odp.out < n.txt
comp tests\14.out tests\14odp.out < n.txt
comp tests\15.out tests\15odp.out < n.txt